# Generated by Django 5.1.4 on 2026-07-03 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cemetery', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('famille_nom', models.CharField(max_length=200)),
                ('famille_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('famille_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('duree', models.CharField(choices=[('10_ans', '10 ans'), ('30_ans', '30 ans'), ('perpetuelle', 'Perpétuelle')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('resiliee', 'Résiliée')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='cemetery.grave')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='concessions_status_78b4a9_idx')],
            },
        ),
    ]
