# Generated by Django 5.1.4 on 2026-07-03 00:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cemetery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defunt_nom', models.CharField(max_length=150)),
                ('defunt_prenom', models.CharField(max_length=150)),
                ('defunt_date_deces', models.DateField()),
                ('famille_nom', models.CharField(max_length=200)),
                ('famille_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('famille_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('archivee', 'Archivée')], default='en_attente', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL)),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cemetery.grave')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='reservation_status_f1a03a_idx')],
            },
        ),
    ]
