# Generated by Django 5.1.4 on 2026-07-03 00:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire'), ('momo', 'MTN Mobile Money')], max_length=20)),
                ('numero_recu', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='concessions.concession')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MomoTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('momo_financial_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESSFUL', 'Réussi'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('payer_message', models.CharField(blank=True, max_length=200, null=True)),
                ('payee_note', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_transactions', to='concessions.concession')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momo_transactions_initiated', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momo_transaction', to='payments.paiement')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['numero_recu'], name='payments_pa_numero__ad703e_idx'),
        ),
        migrations.AddIndex(
            model_name='momotransaction',
            index=models.Index(fields=['status'], name='payments_mo_status_5bb990_idx'),
        ),
        migrations.AddIndex(
            model_name='momotransaction',
            index=models.Index(fields=['reference_id'], name='payments_mo_referen_56f0e5_idx'),
        ),
    ]
