# Generated by Django 5.1.4 on 2026-07-03 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('reserve', 'Réservé'), ('maintenance', 'Maintenance')], default='libre', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graves', to='cemetery.bloc')),
            ],
            options={
                'ordering': ['numero'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
                ('grave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defunts', to='cemetery.grave')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bloc',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='cemetery.section'),
        ),
        migrations.AddIndex(
            model_name='grave',
            index=models.Index(fields=['status'], name='cemetery_gr_status_c6e895_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grave',
            unique_together={('bloc', 'numero')},
        ),
        migrations.AddIndex(
            model_name='defunt',
            index=models.Index(fields=['nom', 'prenom'], name='cemetery_de_nom_b4e644_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bloc',
            unique_together={('section', 'nom')},
        ),
    ]
